---
- name: Subscribe system for openshift-enterprise deployment
  include_tasks: subscription-manager.yml
  when:
  - openshift_deployment_type == 'openshift-enterprise'

- name: Install and uninstall packages
  include_tasks: packages.yml

- name: Enable quotas for root filesystem
  include_tasks: rootfs-quota.yml

- name: Configure for cloud provider
  include_tasks: cloud-provider-{{ demo_cloud_provider }}.yml
