---
- name: Get registry service account key
  shell: >-
    terraform output registry_service_account_key_encrypted |
    base64 -d |
    gpg -d --batch --passphrase {{ demo_gpg_key_passphrase | quote }}
  args:
    chdir: "{{ terraform_dir }}/service-accounts"
  register: get_registry_service_account_key
  changed_when: false

- name: Get registry service account key from config
  command: >-
    ansible-vault decrypt {{ registry_bucket_keyfile | quote }}
    --vault-password-file={{ vault_password_file | quote }}
    --output=-
  register: get_config_registry_service_account_key
  changed_when: false
  failed_when: false

# We need to handle the base64 encoding this way so that ansible doesn't muck up
# the JSON data by auto-transforming the string into a dict.

- name: Update registry service account key
  shell: >-
    base64 -d |
    ansible-vault encrypt -
    --vault-password-file={{ vault_password_file | quote }}
    --output={{ registry_bucket_keyfile | quote }}
  args:
    stdin: "{{ get_registry_service_account_key.stdout }}"
  vars:
    output_key: >-
      {{ get_registry_service_account_key.stdout | b64decode }}
    config_key: >-
      {{ get_config_registry_service_account_key.stdout }}
  when: >-
    output_key != config_key
