---
- name: Run terraform apply for components
  command: terraform apply -auto-approve
  args:
    chdir: "{{ terraform_dir }}/{{ component_name }}"
  register: terraform_apply
  changed_when: >-
    "Resources: 0 added, 0 changed, 0 destroyed." not in terraform_apply.stdout
  with_items:
  - network
  - controller
  - service-accounts
  - registry-storage
  - masters
  - image-node
  loop_control:
    loop_var: component_name
  when: >-
    component_name in terraform_components

- name: Get service account keys
  include_tasks: get-service-account-keys.yml
  when: >-
    'service-accounts' in terraform_components

- name: Run terraform apply for node-group components
  command: terraform apply -auto-approve
  args:
    chdir: "{{ terraform_template_dir }}"
  with_dict: "{{ demo_openshift_node_groups }}"
  loop_control:
    loop_var: node_group_item
  vars:
    node_group: "{{ node_group_item.value }}"
    node_group_name: "{{ node_group_item.key }}"
    terraform_template_dir: "{{ terraform_dir }}/node-group-{{ node_group_name }}"
  when:
  - not node_group.static_node_group|default(false)|bool
  - >-
    'node-group-' ~ node_group_name in terraform_components or
    'node-groups' in terraform_components
  # Terraform template management sometimes fails because it attempts template
  # delete before the instance group updates have completed, so retry
  register: terraform_apply
  until: terraform_apply.rc == 0
  retries: 2
  delay: 5

- name: Run terraform apply for components
  command: terraform apply -auto-approve
  args:
    chdir: "{{ terraform_dir }}/{{ component_name }}"
  register: terraform_apply
  changed_when: >-
    "Resources: 0 added, 0 changed, 0 destroyed." not in terraform_apply.stdout
  with_items:
  - router
  - public-load-balancer
  loop_control:
    loop_var: component_name
  when: >-
    component_name in terraform_components
