#!/bin/sh

USAGE="Usage: $0 <CLUSTER_NAME>"
OPENSHIFT_CLUSTER_NAME="$1"

errexit () {
  echo -e "$1\n$USAGE" >&2
  exit 1
}

[[ -z "$OPENSHIFT_CLUSTER_NAME" ]] && errexit "No OPENSHIFT_CLUSTER_NAME provided."

OPENSHIFT_CONFIG_LOCATION=${OPENSHIFT_CONFIG_LOCATION:-$PWD/config}
OPENSHIFT_CLUSTER_DIR=${OPENSHIFT_CONFIG_LOCATION}/cluster/${OPENSHIFT_CLUSTER_NAME}
OPENSHIFT_CONNECTION_SETTINGS=${OPENSHIFT_CLUSTER_DIR}/openshift-connection.yml
VAULT_PASSWORD_FILE=${VAULT_PASSWORD_FILE:-$PWD/.vaultpw}

[[ -d "$OPENSHIFT_CONFIG_LOCATION" ]] || \
  errexit "OPENSHIFT_CONFIG_LOCATION not found at $OPENSHIFT_CONFIG_LOCATION"
[[ -d "$OPENSHIFT_CLUSTER_DIR" ]] || \
  errexit "Cluster subdirectory not found at $OPENSHIFT_CLUSTER_DIR"
[[ -f "$OPENSHIFT_CONNECTION_SETTINGS" ]] || \
  errexit "OPENSHIFT_CONNECTION_SETTINGS file not found at $OPENSHIFT_CONNECTION_SETTINGS"
[[ -f "$VAULT_PASSWORD_FILE" ]] || \
  errexit "VAULT_PASSWORD_FILE not found at $VAULT_PASSWORD_FILE"

ANSIBLE_VARS="\
--vault-password-file=$VAULT_PASSWORD_FILE \
-e cluster_name=$OPENSHIFT_CLUSTER_NAME \
-e openshift_config_location=$OPENSHIFT_CONFIG_LOCATION \
-e @$OPENSHIFT_CONNECTION_SETTINGS"

export OPENSHIFT_CONFIG_LOCATION OPENSHIFT_CLUSTER_NAME
ansible-playbook $ANSIBLE_VARS openshift-provision.yml
