= OpenShift Provision Demo

OpenShift is inherently complicated. Effectively managing OpenShift is
accomplished by managing its complexity.

In this repository you will find a proven approach to manage OpenShift
3 clusters from cloud infrastructure provisioning, to installation, and
continuing management using ansible, terraform, and a common scalable
configuration structure.

We suggest you begin by running through the Google Cloud (GCP) demo setup
and then explore pushing out a new autoscaling node image, using the
openshift-provision ansible module, and other execrises describe below.

While you may choose to use this repository directly to provision OpenShift
clusters, we encourage you to approach it as a collection of examples and
design pattern to borrow from to build out your own tooling. All code in
this repository is GPLv3.

This demo includes cluster configuration, infrastructure provisioning with
terraform, cluster installation with ansible, and post installation cluster
configuration all in a single repository. You may wish to break these functions
into multiple repositories for your own implementation.

== Prerequisites

For this demo we deploy a virtual server for controlling the cluster, but there
are still some requiremens needed to get the control host up and running:

ansible 2.6+
jq 1.5+
terraform 0.11+

You will need to also need an account cloud provider account with sufficient
access to create the control host and configure the cluster.  At this time GCP
is the only supported cloud provider. Because this demo manages all aspects
of cluster deployment it requires that you have owner access of a GCP project.
We recommend creating an isolated GCP project dedicated for this purpose then
create a service account with owner access to the project and set the
environment variable `GOOGLE_APPLICATION_CREDENTIALS` with the path to your
GCP credentials file.

We include both support for OKD and OCP. If you are using the OCP demo then
you will need to have an OpenShift subscription and set the following
environment variables before configuring your control host:

```
# Credentials used to register systems with subscriptions for software
# installation and updates
export REDHAT_SUBSCRIPTION_USERNAME=... 
export REDHAT_SUBSCRIPTION_PASSWORD=...
export REDHAT_SUBSCRIPTION_POOLS=...

# Credentials for retrieving images from registry.redhat.io
export OREG_AUTH_USER=...
export OREG_AUTH_PASSWORD=...
```

== GCP Setup

FIXME ...

== 

FIXME ...

== Config Repository

The link:config[] directory includes an example of how to lay out a
configuration repositories with an inheritance structure to make it easy to
manage multiple clusters.

== Dynamic Inventory

FIXME ...

== Resource Hierarchy

FIXME ...

== Terraform with Jinja Templates

FIXME ...

== License

GPLv3
