---
# FIXME - Configure webhook key post cluster install, right before run of
# openshift-provision
- name: Read controller generated config
  slurp:
    src: "{{ controller_generate_config_path }}"
  failed_when: false
  register: read_controller_generated_config

- name: Set demo_cluster_webhook_key
  set_fact:
    demo_cluster_webhook_key: >-
      {% if read_controller_generated_config.content | default('') -%}
      {{ read_controller_generated_config.content
       | b64decode
       | from_yaml
       | json_query('demo_cluster_webhook_key')
       | default(999999999999999 | random | to_uuid, true)
      }}
      {%- else -%}
      {{ 999999999999999 | random | to_uuid }}
      {%- endif %}

- name: Controller generated config yaml
  copy:
    dest: "{{ controller_generate_config_path }}"
    content: |
      demo_is_running_from_controller: true
      demo_cluster_webhook_key: {{ demo_cluster_webhook_key | to_json }}
