---
- debug: var=openshift_provision_config_path
- name: Set contents of demo.env
  copy:
    dest: ~/openshift-provision-demo/demo.env
    content: |
      export OPENSHIFT_ANSIBLE_PATH=~/openshift-ansible
      export DEMO_CLUSTER_NAME={{ demo_cluster_name }}
      export OPENSHIFT_PROVISION_PROJECT_DIR=~/openshift-provision-demo
      {% for env_var in subscription_vars %}
      {%   set env_value = lookup('env', env_var) %}
      {%   if env_value != '' %}
      export {{ env_var }}='{{ env_value }}'
      {%   endif %}
      {% endfor %}
  vars:
    subscription_vars:
    - REDHAT_SUBSCRIPTION_USERNAME
    - REDHAT_SUBSCRIPTION_PASSWORD
    - REDHAT_SUBSCRIPTION_POOLS
    - OREG_AUTH_USER
    - OREG_AUTH_PASSWORD
