---
- name: Create gitlab project {{ git_project.name }}
  uri:
    url: http://localhost/api/v4/projects
    method: POST
    body_format: form-urlencoded
    body:
      name: "{{ git_project.name }}"
      description: "{{ git_project.description }}"
      issues_enabled: yes
      merge_requests_enabled: yes
      visibility: public
    headers:
      Authorization: Bearer {{ gitlab_access_token }}
  register: create_demo_project
  changed_when: create_demo_project.status == 201
  failed_when:
  - create_demo_project.status != 201
  - not create_demo_project.json
  - create_demo_project.json.message.name != ["has already been taken"]

- name: Git clone {{ git_project.name }}
  command: git clone {{ git_project.origin_url }}
  args:
    chdir: ~/
    creates: ~/{{ git_project.name }}

- name: Add remote for local gitlab for {{ git_project.name }}
  command: >-
    git remote add gitlab
    http://root:{{ demo_gitlab_root_password }}@localhost/root/{{ git_project.name }}.git
  args:
    chdir: ~/{{ git_project.name }}
  register: add_gitlab_remote
  changed_when: add_gitlab_remote.rc == 0
  failed_when: >-
    add_gitlab_remote.rc != 0 and
    "already exists" not in add_gitlab_remote.stderr

- name: Push {{ git_project.name }} to gitlab
  command: git push gitlab --all
  args:
    chdir: ~/{{ git_project.name }}
  register: git_push
  changed_when: git_push.stderr != "Everything up-to-date"
