---
- name: Get gitlab oauth token
  uri:
    url: http://localhost/oauth/token
    method: POST
    body_format: form-urlencoded
    body:
      grant_type: password
      username: root
      password: "{{ demo_gitlab_root_password }}"
  register: get_oauth_token

- name: Create projects in gitlab
  include_tasks: gitlab-project-create.yml
  with_items:
  - name: openshift-provision-demo
    description: OpenShift Provision Demo
    origin_url: https://github.com/gnuthought/openshift-provision-demo.git
  - name: openshift-provision-manager
    description: OpenShift Provision Manager
    origin_url: https://github.com/gnuthought/openshift-provision-manager.git
  - name: openshift-provision-example-0
    description: OpenShift Provision Example 0
    origin_url: https://github.com/gnuthought/openshift-provision-example-0.git
  - name: openshift-provision-example-1
    description: OpenShift Provision Example 1
    origin_url: https://github.com/gnuthought/openshift-provision-example-1.git
  - name: openshift-provision-example-2
    description: OpenShift Provision Example 2
    origin_url: https://github.com/gnuthought/openshift-provision-example-2.git
  loop_control:
    loop_var: git_project
  vars:
    gitlab_access_token: "{{ get_oauth_token.json.access_token }}"
