---
- name: Stat /usr/local/bin/terraform
  become: true
  stat:
    path: /usr/local/bin/terraform
  register: check_terraform

- when: not check_terraform.stat.exists
  block:
  - name: Get terraform
    become: true
    get_url:
      url: >-
        https://releases.hashicorp.com/terraform/{{
          demo_controller_terraform_release
        }}/terraform_{{
          demo_controller_terraform_release
        }}_linux_amd64.zip
      dest: >-
        /usr/local/src/terraform_{{
          demo_controller_terraform_release
        }}_linux_amd64.zip

  - name: Unpack terraform
    become: true
    command: >-
      unzip /usr/local/src/terraform_{{
        demo_controller_terraform_release
      }}_linux_amd64.zip
    args:
      chdir: /usr/local/bin
