---
- name: Install subscription-manager package
  become: true
  yum:
    name: subscription-manager
    state: present

- name: Register controller with subscription-manager
  become: true
  redhat_subscription:
    username: "{{ demo_rhsub_user }}"
    password: "{{ demo_rhsub_pass }}"
    pool_ids: "{{ demo_rhsub_pool }}"
  register: redhat_subscribe_system

- name: Set yum repositories
  become: true
  command: >-
    subscription-manager repos
    --disable='*'
    --enable=rhel-7-server-ansible-2.6-rpms
    --enable=rhel-7-server-extras-rpms
    --enable=rhel-7-server-ose-{{ openshift_release }}-rpms
    --enable=rhel-7-server-optional-rpms
    --enable=rhel-7-server-rpms
  when: redhat_subscribe_system.changed
  register: set_yum_repositories

- name: Remove cloud repos
  become: true
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - /etc/yum.repos.d/google-cloud.repo
  - /etc/yum.repos.d/rh-cloud.repo
  register: remove_cloud_repos

- name: Check if epel yum repository is configured
  become: true
  stat:
    path: /etc/yum.repos.d/epel.repo
  register: epel_repo_stat

- name: Disable epel repository
  become: true
  replace:
    path: /etc/yum.repos.d/epel.repo
    regexp: ^enabled=1
    replace: enabled=0
  when: epel_repo_stat.stat.exists

- when: >-
    set_yum_repositories.changed or
    remove_cloud_repos.changed
  block:
  - name: Yum clean
    become: true
    command: yum clean all
    args:
      warn: false

  - name: Remove yum cache
    become: true
    file:
      path: /var/cache/yum
      state: absent
