---
#
# Secret values in this file may be managed as environment variables or directly
# stored in this file. If credetials are store directly then this file should be
# encrypted with ansible vault.
#

# Values for accessing images from registry.redhat.io
oreg_auth_user: "{{ lookup('env', 'OREG_AUTH_USER') }}"
oreg_auth_password: "{{ lookup('env', 'OREG_AUTH_PASSWORD') }}"

# Values used to subscribe system to Red Hat for software installation and updates
demo_rhsub_user: "{{ lookup('env', 'REDHAT_SUBSCRIPTION_USERNAME') }}"
demo_rhsub_pass: "{{ lookup('env', 'REDHAT_SUBSCRIPTION_PASSWORD') }}"
demo_rhsub_pool: "{{ lookup('env', 'REDHAT_SUBSCRIPTION_POOLS') }}"
