---
- name: Get webhook secret for {{ project.config }}
  command: >-
    oc get secret -n openshift-provision {{ project.config }}-webhook
    -o jsonpath='{.data.key}'
  register: get_webhook_secret
  changed_when: false
 
- name: Get webhooks for {{ project.repo }}
  uri:
    url: http://localhost/api/v4/projects/root%2F{{ project.repo }}/hooks
    method: GET
    headers:
      Authorization: Bearer {{ gitlab_access_token }}
  delegate_to: localhost
  register: get_webhooks

- name: Add webhook for {{ project.config }}
  uri:
    url: http://localhost/api/v4/projects/root%2F{{ project.repo }}/hooks
    method: POST
    body_format: json
    body:
      id: cluster
      url: "{{ webhook_url }}"
      push_events: true
      push_events_branch_filter: "master"
      enable_ssl_verification: false
    headers:
      Authorization: Bearer {{ get_oauth_token.json.access_token }}
  vars:
    webhook_url: >-
     {{ 'https://manager-openshift-provision.'
      ~ openshift_master_default_subdomain
      ~ '/provision/'
      ~ project.config ~ '/'
      ~ get_webhook_secret.stdout | b64decode
     }}
  when: >-
    0 == get_webhooks.json | json_query("[?url=='" ~ webhook_url ~ "']") | length
  delegate_to: localhost
  register: create_webhook
  changed_when: create_webhook.status == 201
  failed_when:
  - create_webhook.status != 201
