---
- name: Run terrafom apply
  hosts: localhost
  connection: local
  tasks:
  - name: Load cluster config
    import_tasks: ../load-dynamic-config.yml

  - name: Include terraform role to create controller
    include_role:
      name: "{{ demo_cloud_provider }}-terraform"
      allow_duplicates: true
    vars:
      terraform_action: apply
      terraform_components:
      - network
      - controller
      terraform_dir: "{{ playbook_dir }}/terraform/{{ demo_cluster_name }}"

  - name: Wait for controller to be running
    command: ../hosts.py --wait 300
    environment:
      ANSIBLE_GROUP_FILTER: controller
    changed_when: false

  - name: Refresh inventory
    meta: refresh_inventory
