---
#
# If demo_management_source_ip_range is not defined then it is set based on the
# current host's apparent public ip address.
#

- when:
  - demo_management_source_ip_range is not defined
  - not demo_is_running_from_controller|default(False)
  block:
  - name: Determine public ip address
    uri:
      url: http://ipv4bot.whatismyipaddress.com/
      return_content: true
    register: get_whatismyipaddress

  - name: Set demo_management_source_ip_range
    set_fact:
      demo_management_source_ip_range: "{{ get_whatismyipaddress.content }}/32"
