---
cluster_ansible_ssh_pubkey: >-
  {{ demo_ansible_ssh_pubkey }}
cluster_ansible_user: >-
  {{ demo_ansible_user }}
cluster_name: >-
  {{ demo_cluster_name }}
cluster_subnetwork_name: >-
  {{ openshift_gcp_subnetwork_name }}
cluster_subnetwork_ip_cidr_range: >-
  {{ demo_gcp_subnetwork_ip_cidr_range }}

cluster_dns_domain: >-
  {{ demo_dns_cluster_domain }}
cluster_dns_zone_name: >-
  {{ demo_gcp_dns_zone_name }}

use_controller: >-
  {{ demo_use_controller }}
controller_ansible_port: >-
  {{ demo_controller_ansible_port }}
controller_ansible_ssh_pubkey: >-
  {{ demo_controller_ansible_ssh_pubkey }}
controller_ansible_user: >-
  {{ demo_controller_ansible_user }}
controller_boot_disk_image: >-
  {{ demo_gcp_controller_boot_disk_image }}
controller_boot_disk_size_gb: >-
  {{ demo_gcp_controller_boot_disk_size_gb }}
controller_hostname: >-
  {{ demo_controller_hostname }}
controller_iam_roles: >-
  {{ demo_gcp_controller_iam_roles }}
controller_machine_type: >-
  {{ demo_gcp_controller_machine_type }}
controller_service_account: >-
  {{ demo_gcp_controller_service_account }}

delegation_dns_zone_name: >-
  {{ demo_gcp_dns_delegation_zone_name }}
handle_dns_delegation: >-
  {{ demo_handle_dns_delegation }}
use_cloud_dns: >-
  {{ demo_use_cloud_dns }}

gcp_zones: >-
  {{ demo_gcp_zones }}

image_node_group: >-
  {{ demo_openshift_node_groups.image }}
image_node_group_gcp: >-
  {{ image_node_group.gcp | default({}) }}
image_node_boot_disk_image: >-
  {{ openshift_gcp_image }}
image_node_boot_disk_size_gb: >-
  {{ image_node_group_gcp.boot_disk_size_gb
   | default(demo_gcp_node_boot_disk_size_gb)
  }}
image_node_boot_disk_type: >-
  {{ image_node_group_gcp.boot_disk_type
   | default(demo_gcp_node_boot_disk_type)
  }}
image_node_machine_type: >-
  {{ image_node_group_gcp.machine_type
   | default(demo_gcp_node_machine_type)
  }}
management_source_ip_range: >-
  {{ demo_management_source_ip_range | default('') }}

master_node_group: >-
  {{ demo_openshift_node_groups.master }}
master_node_group_gcp: >-
  {{ master_node_group.gcp | default({}) }}
master_boot_disk_image: >-
  {{ demo_gcp_master_boot_disk_image }}
master_boot_disk_size_gb: >-
  {{ master_node_group_gcp.boot_disk_size_gb
   | default(demo_gcp_master_boot_disk_size_gb)
  }}
master_boot_disk_type: >-
  {{ master_node_group_gcp.boot_disk_type
   | default(demo_gcp_master_boot_disk_type)
  }}
master_docker_vg_disk_size_gb: >-
  {{ master_node_group_gcp.docker_vg_disk_size_gb
   | default(demo_gcp_master_docker_vg_disk_size_gb)
  }}
master_docker_vg_disk_type: >-
  {{ master_node_group_gcp.docker_vg_disk_type
   | default(demo_gcp_master_docker_vg_disk_type)
  }}
master_machine_type: >-
  {{ master_node_group_gcp.machine_type
   | default(demo_gcp_master_machine_type)
  }}
master_service_account: >-
  {{ demo_gcp_master_service_account }}

node_image_family: >-
  {{ demo_gcp_node_image_family }}
node_service_account: >-
  {{ demo_gcp_node_service_account }}

create_registry_bucket: >-
  {{ openshift_gcp_create_registry_bucket | bool }}
registry_bucket_keyfile:  >-
  {{ openshift_gcp_registry_bucket_keyfile }}
registry_bucket_name: >-
  {{ openshift_gcp_registry_bucket_name }}
registry_service_account_id: >-
  {{ demo_gcp_registry_service_account_id }}

use_shared_public_load_balancer: >-
  {{ demo_shared_public_load_balancer }}
