---
- name: Get master.crt subject
  command: >-
    openssl x509 -subject -noout
    -in {{ demo_cluster_tls_dir }}/master.crt
  changed_when: false
  failed_when: false
  register: get_master_crt_subject

- name: Check if master.crt is self-signed
  command: >-
    diff -q
    {{ demo_cluster_tls_dir }}/master.crt
    {{ demo_cluster_tls_dir }}/master-ca.crt
  changed_when: false
  failed_when: false
  register: check_master_crt_self_signed

- name: Remove self-signed master certs and key
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ demo_cluster_tls_dir }}/master.key"
  - "{{ demo_cluster_tls_dir }}/master.crt"
  - "{{ demo_cluster_tls_dir }}/master-ca.crt"
  vars:
    master_subject: >-
      {{ get_master_crt_subject.stdout
       | default('')
       | regex_replace('.*CN=', '')
      }}
  when:
  - check_master_crt_self_signed.rc == 0
  - master_subject != openshift_master_cluster_public_hostname

- name: Create self-signed master public cert
  command: >-
    openssl req -new -nodes -x509
    -newkey rsa:2048
    -days 365
    -keyout {{ demo_cluster_tls_dir }}/master.key
    -out {{ demo_cluster_tls_dir }}/master.crt
    -subj '/CN={{ openshift_master_cluster_public_hostname }}'
  args:
    creates: "{{ demo_cluster_tls_dir }}/master.crt"
  register: create_master_certificate

- when: create_master_certificate.changed
  name: Copy master self signed sert to master-ca.crt
  copy:
    remote_src: true
    src: "{{ demo_cluster_tls_dir }}/master.crt"
    dest: "{{ demo_cluster_tls_dir }}/master-ca.crt"

- name: Copy master ca cert to /etc/pki/ca-trust/source/anchors
  become: true
  copy:
    remote_src: true
    src: "{{ demo_cluster_tls_dir }}/master-ca.crt"
    dest: /etc/pki/ca-trust/source/anchors/{{ demo_cluster_name }}-master-ca.crt
  ignore_errors: true
  notify: update-ca-trust
