---
- name: Get router.crt subject
  command: >-
    openssl x509 -subject -noout
    -in {{ demo_cluster_tls_dir }}/router.crt
  changed_when: false
  failed_when: false
  register: get_router_crt_subject

- name: Check if router.crt is self-signed
  command: >-
    diff -q
    {{ demo_cluster_tls_dir }}/router.crt
    {{ demo_cluster_tls_dir }}/router-ca.crt
  changed_when: false
  failed_when: false
  register: check_router_crt_self_signed

- name: Remove self-signed router certs and key
  file:
    path: "{{ item }}"
    state: absent
  with_items:
  - "{{ demo_cluster_tls_dir }}/router.key"
  - "{{ demo_cluster_tls_dir }}/router.crt"
  - "{{ demo_cluster_tls_dir }}/router-ca.crt"
  vars:
    router_subject: >-
      {{ get_router_crt_subject.stdout
       | default('')
       | regex_replace('.*CN=', '')
      }}
  when:
  - check_router_crt_self_signed.rc == 0
  - router_subject != '*.' ~ openshift_master_default_subdomain

- name: Create self-signed router cert
  command: >-
    openssl req -new -nodes -x509
    -newkey rsa:2048
    -days 365
    -keyout {{ demo_cluster_tls_dir }}/router.key
    -out {{ demo_cluster_tls_dir }}/router.crt
    -subj '/CN=*.{{ openshift_master_default_subdomain }}'
  args:
    creates: "{{ demo_cluster_tls_dir }}/router.crt"
  register: create_router_certificate

- name: Copy router self signed sert to router-ca.crt
  when: create_router_certificate.changed
  copy:
    remote_src: true
    src: "{{ demo_cluster_tls_dir }}/router.crt"
    dest: "{{ demo_cluster_tls_dir }}/router-ca.crt"

- name: Copy router ca cert to /etc/pki/ca-trust/source/anchors
  become: true
  copy:
    remote_src: true
    src: "{{ demo_cluster_tls_dir }}/router-ca.crt"
    dest: /etc/pki/ca-trust/source/anchors/{{ demo_cluster_name }}-router-ca.crt
  register: copy_router_ca_cert_to_anchors
  notify: update-ca-trust

- when: use_shared_public_load_balancer
  block:
  - name: Copy router self signed key to master
    copy:
      remote_src: true
      src: "{{ demo_cluster_tls_dir }}/router.key"
      dest: "{{ demo_cluster_tls_dir }}/master.key"
  - name: Copy router self signed cert to master
    copy:
      remote_src: true
      src: "{{ demo_cluster_tls_dir }}/router.crt"
      dest: "{{ demo_cluster_tls_dir }}/master.crt"
  - name: Copy router self signed ca cert to master
    copy:
      remote_src: true
      src: "{{ demo_cluster_tls_dir }}/router-ca.crt"
      dest: "{{ demo_cluster_tls_dir }}/master-ca.crt"
