---
- name: Load dynamic config
  hosts: OSEv3
  tasks:
  - name: Load dynamic config
    import_tasks: ../load-dynamic-config.yml

- import_playbook: >-
   {{ demo_openshift_ansible_path }}/playbooks/init/main.yml
  vars:
    l_networkman_check_hosts: "oo_nodes_to_config"

- import_playbook: >-
   {{ demo_openshift_ansible_path }}/playbooks/common/private/components.yml

- import_playbook: replace-passthrough-routes.yml
