---
- import_playbook: terraform-configure.yml
- import_playbook: bootstrap-install.yml
- import_playbook: cluster-config.yml
- import_playbook: cluster-vars.yml
- import_playbook: openshift-provision.yml
