---
- name: OpenShift Provision
  hosts: masters[0]
  gather_facts: false
  pre_tasks:
  - name: Load dynamic config
    import_tasks: ../load-dynamic-config.yml
  roles:
  - role: openshift-provision
