---
- name: Run terraform destroy
  hosts: localhost
  connection: local
  tasks:
  - name: Load dynamic config
    import_tasks: ../load-dynamic-config.yml

  - name: Include terraform role for destroy
    include_role:
      name: "{{ demo_cloud_provider }}-terraform"
      allow_duplicates: true
    vars:
      terraform_action: destroy
      terraform_components:
      - public-load-balancer
      - router
      - image-node
      - node-groups
      - masters
      - registry-storage
      - service-accounts
      terraform_dir: "{{ playbook_dir }}/terraform/{{ demo_cluster_name }}"
