---
- name: Run terrafom deploy
  hosts: localhost
  connection: local
  tasks:
  - name: Load dynamic config
    import_tasks: ../load-dynamic-config.yml

  - name: Include terraform role for deploy
    include_role:
      name: "{{ demo_cloud_provider }}-terraform"
      allow_duplicates: true
    vars:
      terraform_action: apply
      terraform_components:
      - node-groups
      - router
      - public-load-balancer
      terraform_dir: "{{ playbook_dir }}/terraform/{{ demo_cluster_name }}"

  - name: Scale-up cluster
    command: ../hosts.py --scaleup

  - name: Wait for all instances to be running
    command: ../hosts.py --wait 300
    changed_when: false

  - name: Refresh inventory
    meta: refresh_inventory

- name: Wait for connection to scaled instances
  hosts: OSEv3
  gather_facts: false
  tasks:
  - name: Wait for connection to instances
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
