---
demo_controller_packages_enablerepo: []

demo_controller_cloud_packages: []

demo_controller_cloud_packages_enablerepo: []

demo_controller_cloud_python_packages: []

demo_openshift_ansible_git_repo: https://github.com/openshift/openshift-ansible.git
demo_openshift_ansible_git_branch: release-{{ openshift_release }}

demo_gitlab_root_password: password
