---
demo_cluster_vars_for_cloud_provider:
  gcp_project: "{{ openshift_gcp_project }}"
  gcp_region: "{{ openshift_gcp_region }}"
  gcp_zones: "{{ demo_gcp_zones | join(',') }}"

# Set by dynamic inventory
openshift_gcp_project: ''
