---
demo_controller_cloud_packages:
- python2-google-api-client

demo_controller_cloud_packages_enablerepo:
- epel

demo_controller_cloud_python_packages: []

demo_gcp_controller_iam_roles:
- owner

#demo_gcp_controller_boot_disk_image: >-
#  {{ 'centos-7' if openshift_deployment_type == 'origin' else 'rhel-7' }}
#demo_gcp_controller_boot_disk_size_gb: 50
#demo_gcp_controller_machine_type: n1-standard-1
#demo_gcp_controller_service_account: "{{ openshift_gcp_prefix }}controller"
