---
openshift_cloudprovider_kind: gce
openshift_gcp_prefix: "{{ demo_cluster_name }}-"
openshift_gcp_multizone: true
demo_gcp_node_image_family: "{{ openshift_gcp_prefix }}node"

# FIXME - Support these settings
#openshift_gcp_create_registry_bucket: true
#openshift_gcp_clusterid: default
#openshift_gcp_master_lb_timeout: 2m
#openshift_gcp_registry_bucket_keyfile: ''
#openshift_gcp_registry_bucket_name: "{{ openshift_gcp_prefix }}-docker-registry"

demo_gcp_use_fqdn: false

# Google requires GCS bucket names to be globally unique. Prepending the gcp
# project name helps ensure this is the case.
demo_gcp_terraform_state_bucket: >-
  {{ openshift_provision_cluster_vars.gcp_project }}-{{ openshift_gcp_prefix }}terraform-state
