---
openshift_gcp_network_name: "{{ demo_cluster_name }}"
openshift_gcp_network_project: "{{ openshift_provision_cluster_vars.gcp_project }}"
openshift_gcp_subnetwork_name: "{{ demo_cluster_name }}"
#demo_gcp_subnetwork_ip_cidr_range: "10.0.0.0/24"

demo_gcp_dns_zone_name: "{{ demo_cluster_name }}"
