---
openshift_gcp_prefix: demo-sbx-okd3-
demo_gcp_dns_delegation_zone_name: openshift-gnuthought-com
demo_gcp_controller_machine_type: n1-standard-1
demo_gcp_master_machine_type: n1-standard-2
demo_gcp_node_machine_type: n1-standard-1
